jwt:
  expirationMs: 3600000
  refreshExpirationMs: 360000000
  secret: qqaadsasdsdsdsdswwe
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      enabled: 'true'
      max-request-size: 1000MB
  datasource:
    password: AaBeGD56H21ha53g64AhHBaBHb3b4Dd3
    username: root
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:45141:railway
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

app:

server:
  port: 8810
  error:
    include-message: always


